### ISSUE TITLE
Preview Fonts Section link is not working

### ISSUE THREAD

**Issue by guti7** [thelioncape/San-Francisco-family#2]
The link to try out fonts is no longer active.

**Comment by thelioncape** [comment]
That's probably because this repo is a fork of another repo that doesn't exist anymore. Do you have any suggestions on how to replicate that feature?

**Comment by jeanthom** [comment]
Hi,

You need to enable GitHub pages in your repository settings:

![GitHub pages settings for a repository](https://github.com/user-attachments/assets/b81d771a-a0a0-400a-8f85-5045f812584a)

Choose the ` master` branch here. Then update all URLs to match your username.

**Comment by thelioncape** [comment]
This should be fixed in commit [084a6ff](https://github.com/thelioncape/San-Francisco-family/commit/084a6ff7f58aba2e0a8c7a7e549a5e2a4fe14b5a)
